const SAMPLE_MUTATIONS_PLUS = 'SAMPLE_MUTATIONS_PLUS';
const SAMPLE_ACTIONS_PLUS = 'SAMPLE_ACTIONS_PLUS';
const SAMPLE_ACTIONS_PLUS_ASYNC = 'SAMPLE_ACTIONS_PLUS_ASYNC';

export default {
    SAMPLE_MUTATIONS_PLUS,
    SAMPLE_ACTIONS_PLUS,
    SAMPLE_ACTIONS_PLUS_ASYNC
};