export const USER_ACTION_LOGIN = 'USER_ACTION_LOGIN';
export const USER_ACTION_REGISTER = 'USER_ACTION_REGISTER';
export const USER_ACTION_CHECK = 'USER_ACTION_CHECK';
export const USER_ACTION_LOGOUT = 'USER_ACTION_LOGOUT';
export const USER_MUTATION_SET_TOKEN = 'USER_MUTATION_SET_TOKEN';
export const USER_MUTATION_SET_ID = 'USER_MUTATION_SET_ID';
export const USER_MUTATION_SET_USERNAME = 'USER_MUTATION_SET_USERNAME';
export const USER_MUTATION_SET_CHECK = 'USER_MUTATION_SET_CHECK';

export const IMG_ACTION_UPLOAD = 'IMG_ACTION_UPLOAD';
export const IMG_ACTION_REMOVE = 'IMG_ACTION_REMOVE';
export const IMG_ACTION_GETLIST = 'IMG_ACTION_GETLIST';
export const IMG_MUTATION_SET_IMGLIST = 'IMG_MUTATION_SET_IMGLIST';
