export const USER_ACTION_LOGIN = 'USER_ACTION_LOGIN';
export const USER_ACTION_REGISTER = 'USER_ACTION_REGISTER';
export const USER_ACTION_CHECK = 'USER_ACTION_CHECK';
export const USER_ACTION_LOGOUT = 'USER_ACTION_LOGOUT';
export const USER_MUTATION_SET_TOKEN = 'USER_MUTATION_SET_TOKEN';
export const USER_MUTATION_SET_ID = 'USER_MUTATION_SET_ID';
export const USER_MUTATION_SET_USERNAME = 'USER_MUTATION_SET_USERNAME';
export const USER_MUTATION_SET_CHECK = 'USER_MUTATION_SET_CHECK';
