export const MUTATION_USER_LOGIN_START = 'MUTATION_USER_LOGIN_START';
export const MUTATION_USER_LOGIN_FAILED = 'MUTATION_USER_LOGIN_FAILED';
export const MUTATION_USER_LOGIN_SUCCESS = 'MUTATION_USER_LOGIN_SUCCESS';
export const MUTATION_USER_LOGOUT = 'MUTATION_USER_LOGOUT';

export const MUTATION_USER_REGISTER_START = 'MUTATION_USER_REGISTER_START';
export const MUTATION_USER_REGISTER_FAILED = 'MUTATION_USER_REGISTER_FAILED';

export const ACTION_USER_TOLOGIN = 'ACTION_USER_TOLOGIN';
export const ACTION_USER_TOLOGOUT = 'ACTION_USER_TOLOGOUT';
export const ACTION_USER_TOREGISTER = 'ACTION_USER_TOREGISTER';

export const MUTATION_IMG_PUSHIMG = 'MUTATION_IMG_PUSHIMG';
export const MUTATION_IMG_REMOVEIMG = 'MUTATION_IMG_REMOVEIMG';

export const ACTION_IMG_TOUPLOADIMG = 'ACTION_IMG_TOUPLOADIMG';
export const ACTION_IMG_TOUPLOADALLIMG = 'ACTION_IMG_TOUPLOADALLIMG';