export const MUTATION_USER_SETUID = 'USER_SETUID';
export const MUTATION_USER_SETTOKEN = 'USER_SETTOKEN';

export const ACTION_USER_TOLOGIN = 'ACTION_USER_TOLOGIN';
export const ACTION_USER_TOREGISTER = 'ACTION_USER_TOREGISTER';


export const MUTATION_IMG_PUSHIMG = 'MUTATION_IMG_PUSHIMG';
export const MUTATION_IMG_REMOVEIMG = 'MUTATION_IMG_REMOVEIMG';

export const ACTION_IMG_TOUPLOADIMG = 'ACTION_IMG_TOUPLOADIMG';
export const ACTION_IMG_TOUPLOADALLIMG = 'ACTION_IMG_TOUPLOADALLIMG';